# @package _global_

model:
  type: 'rnn'
  
ts:
  name: 'weather_gru'
  version: 1
  enrich: ['hour']
  use_covariates: false

model_configs:
  cat_emb_dim: 16
  hidden_RNN: 512
  num_layers_RNN: 3
  kernel_size_encoder: 5
  kind: 'gru'
  sum_emb: true


train_config:
  batch_size: 256
  max_epochs: 250
            
